### PR TITLE
Feature/contents

### PR DESCRIPTION
**Pull request by adamstruck**

### CODE REVIEW

**Comment by buchanae** [comment]
Code looks ok, but how does this pass input validation in the task runner? Needs a test before merging.

**Comment by adamstruck** [comment]
`validateInputs` uses the inputs from the mapper.  When a file is created from the passed 'contents' that input is not added to mapper.Inputs. 

I'll write some tests to demonstrate the behavior.

**Comment by buchanae** [comment]
Makes sense. Thanks.

**Comment by adamstruck** [comment]
Added a test for the file mapper as a whole.

**Comment by buchanae** [comment]
Could you add a ioutil.ReadFile to the test that checks the file that was created by task input contents?

**Comment by adamstruck** [comment]
Done

**Pull request merged**
