### PR TITLE
database: add badger

### LINKED ISSUE #151: Create Badger database backend
Badger is an embedded KV store which supports high write throughput because it doesn't lock the database on writes, the way BoltDB does.

Initial work here:
https://github.com/buchanae/funnel/tree/stress-work/server/badger

### PR DESCRIPTION
**Pull request by buchanae**
closes #151 

Needs:
- [ ] testing
- [ ] website docs

### CODE REVIEW

**Comment by buchanae** [comment]
This might be blocked for awhile. There was a [breaking change](https://github.com/golang/net/commit/cbb82b59bc5199680c5bf34109e12097095dca9b) in `golang.org/x/net` today, which I had unvendored to get around another issue with multiple vendors importing `golang.org/x/net`. I've asked for guidance [here](https://groups.google.com/forum/#!topic/golang-nuts/JiA1j9ZqFwA). Hopefully it's just late and I'm missing something obvious.

**Comment by adamstruck** [comment]
I was able to get things working. I kept all the packages in `golang.org/x` vendored and pulled down their latest code.  Additionally I pulled down the latest from `minio-go`.

**Comment by buchanae** [comment]
Ah, great, thank you. I hadn't thought to update minio-go, I thought maybe docker was the one causing trouble.

**Comment by adamstruck** [comment]
closing in favor of #556

**Pull request closed without merging**
