### PR TITLE
events: tail and rate limit stdout/err logs

### LINKED ISSUE #265: elastic: could limit maximum size of task stdout/err logs
Elasticsearch database does not currently apply any limits to the size of a task's stdout/err logs. It also stores each individual task event. It could apply limits to both of these.

### PR DESCRIPTION
**Pull request by buchanae**
This aims to clean up the log tailing code.
- moved to events package
- made event writing non-blocking, so stdout/err streams are less likely to be blocked on network calls
- included rate limiter (#35)
- events are now the entire tail, instead of small chunks
- logs are always tailed, even if stdout/err are not set in the task (#286)

TODO:
- [x] Ensure that #48 is fixed. 
- [x] Rewrite database log storage to accept entire tail content and remove any server-side trimming (will fix #265)
  - [x] Boltdb
  - [x] Elasticsearch
  - [x] Dynamo

I think sending the whole tail is worth trying. It simplifies everything substantially, especially the database models, and it opens up new opportunities for writing logs to other datastores such as memcache/redis, where we can grab content efficiently without hitting the database. Thinking about logs as a stream of small chunks has been too complex for us to manage, I think.

### CODE REVIEW

**Comment by buchanae** [comment]
Another issue is that the logs should be flushed before the final state is written, so that logs exist before the state changes to a final state.

**Comment by adamstruck** [comment]
you should also address #247 here.

**Comment by buchanae** [comment]
The latest commit uses Elasticsearch scripts to do the task updates, and field filtering to do the task views, which worked out really nicely.

**Comment by adamstruck** [comment]
Here are the changes needed for dynamo:

```patch
diff --git a/events/dynamodb_writer.go b/events/dynamodb_writer.go
index 9808ed4..bfedd34 100644
--- a/events/dynamodb_writer.go
+++ b/events/dynamodb_writer.go
@@ -282,24 +282,13 @@ func (ew *DynamoDBEventWriter) Write(e *Event) error {
                        ExpressionAttributeNames: map[string]*string{
                                "#index": aws.String("index"),
                        },
-                       UpdateExpression: aws.String("SET stdout = list_append(if_not_exists(stdout, :e), :stdout), attempt = :attempt, #index = :index"),
+                       UpdateExpression: aws.String("SET stdout = :stdout, attempt = :attempt, #index = :index"),
                        ExpressionAttributeValues: map[string]*dynamodb.AttributeValue{
                                ":e": {
                                        L: []*dynamodb.AttributeValue{},
                                },
                                ":stdout": {
-                                       L: []*dynamodb.AttributeValue{
-                                               {
-                                                       M: map[string]*dynamodb.AttributeValue{
-                                                               "value": {
-                                                                       S: aws.String(e.GetStdout()),
-                                                               },
-                                                               "timestamp": {
-                                                                       S: aws.String(ptypes.TimestampString(ptypes.TimestampNow())),
-                                                               },
-                                                       },
-                                               },
-                                       },
+                                       S: aws.String(e.GetStdout()),
                                },
                                ":attempt": {
                                        N: aws.String(strconv.Itoa(int(e.Attempt))),
@@ -325,24 +314,13 @@ func (ew *DynamoDBEventWriter) Write(e *Event) error {
                        ExpressionAttributeNames: map[string]*string{
                                "#index": aws.String("index"),
                        },
-                       UpdateExpression: aws.String("SET stderr = list_append(if_not_exists(stderr, :e), :stderr), attempt = :attempt, #index = :index"),
+                       UpdateExpression: aws.String("SET stderr = :stderr, attempt = :attempt, #index = :index"),
                        ExpressionAttributeValues: map[string]*dynamodb.AttributeValue{
                                ":e": {
                                        L: []*dynamodb.AttributeValue{},
                                },
-                               ":stderr": {
-                                       L: []*dynamodb.AttributeValue{
-                                               {
-                                                       M: map[string]*dynamodb.AttributeValue{
-                                                               "value": {
-                                                                       S: aws.String(e.GetStderr()),
-                                                               },
-                                                               "timestamp": {
-                                                                       S: aws.String(ptypes.TimestampString(ptypes.TimestampNow())),
-                                                               },
-                                                       },
-                                               },
-                                       },
+                               ":stderr": {
+                                       S: aws.String(e.GetStderr()),
                                },
                                ":attempt": {
                                        N: aws.String(strconv.Itoa(int(e.Attempt))),
@@ -355,6 +333,6 @@ func (ew *DynamoDBEventWriter) Write(e *Event) error {
                }
        }

-       _, err = ew.client.UpdateItem(item)
+       _, err := ew.client.UpdateItem(item)
        return err
 }
diff --git a/server/dynamodb/util.go b/server/dynamodb/util.go
index 7e3e34b..6084b34 100644
--- a/server/dynamodb/util.go
+++ b/server/dynamodb/util.go
@@ -9,9 +9,7 @@ import (
        "github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
        "github.com/golang/protobuf/ptypes"
        "github.com/ohsu-comp-bio/funnel/proto/tes"
-       "sort"
        "strconv"
-       "time"
 )

 func checkCreateErr(err error) error {
@@ -416,16 +414,7 @@ func (db *DynamoDB) getExecutorOutput(ctx context.Context, in map[string]*dynamo
                        for _, item := range page.Items {
                                i, _ := strconv.ParseInt(*item["index"].N, 10, 64)
                                a, _ := strconv.ParseInt(*item["attempt"].N, 10, 64)
-                               var logs elogs
-                               for _, part := range item[val].L {
-                                       t, _ := time.Parse(time.RFC3339, *part.M["timestamp"].S)
-                                       logs = append(logs, elog{val: *part.M["value"].S, timestamp: t})
-                               }
-                               sort.Sort(logs)
-                               var out string
-                               for _, v := range logs {
-                                       out += v.val
-                               }
+                               out := *item["stdout"].N
                                in["logs"].L[a].M["logs"].L[i].M[val] = &dynamodb.AttributeValue{
                                        S: aws.String(out),
                                }
@@ -441,22 +430,3 @@ func (db *DynamoDB) getExecutorOutput(ctx context.Context, in map[string]*dynamo
        }
        return nil
 }
-
-type elog struct {
-       val       string
-       timestamp time.Time
-}
-
-type elogs []elog
-
-func (slice elogs) Len() int {
-       return len(slice)
-}
-
-func (slice elogs) Less(i, j int) bool {
-       return slice[i].timestamp.Before(slice[j].timestamp)
-}
-
-func (slice elogs) Swap(i, j int) {
-       slice[i], slice[j] = slice[j], slice[i]
-}
```

**Pull request merged**
