### PR TITLE
Funnel run

### PR DESCRIPTION
**Pull request by adamstruck**
Picking up from #61

### CODE REVIEW

**Comment by adamstruck** [comment]
This now works:

```
funnel run 'md5sum $FILE > $OUT' --in FILE=file:///tmp/file.txt --image ubuntu --out OUT=file:///tmp/test_out
```

**Comment by buchanae** [comment]
- default server address should be "http://localhost:8000"
- remove "stringSlice" from help
- remove "vars-file"
- make image an arg
- help should include example of input, output, env var format e.g. "key=val"
- the flags shouldn't be sorted by name if possible, but rather grouped by concept (most common in/out/env, metadata, resources, etc)

**Comment by buchanae** [comment]
- "--print" shows debug logs which threw me off. Also, pretty printing the JSON would be a nice default to have

**Comment by buchanae** [comment]
- automatically prefix "file://"

**Comment by buchanae** [comment]
- '--stdin' and '--stdout' flags would be useful
- directory input

**Comment by adamstruck** [comment]
Remaining TODO's tracked in #105

**Pull request merged**
