### PR TITLE
Python packaging

### PR DESCRIPTION
**Pull request by buchanae**
Putting this here so I don't forget about it. Needs some cleanup.

### CODE REVIEW

**Comment by adamstruck** [comment]
Python package now lives at https://github.com/ohsu-comp-bio/py-tes

**Comment by adamstruck** [comment]
Will close once we remove this code from Funnel

**Comment by buchanae** [comment]
Changed the PR to remove the python directory and related .gitignore.

**Comment by adamstruck** [comment]
Would you also update the Makefile to remove the python specific bits from `tidy` and `lint`?

**Comment by buchanae** [comment]
Done, thanks.

**Pull request merged**
