### PR TITLE
webdash: style, cleanup, pagination, fixes

### LINKED ISSUE #293: webdash: current task count in node list
I've found that for administration, it would be really nice if the dashboard included a little more info in the node list, such as how many tasks it currently has running. This would allow me to quickly scan to see how busy the cluster is.

### PR DESCRIPTION
**Pull request by buchanae**
Closes #293, #284, #280, #255. Also makes a bunch of style changes, hopefully you agree it's cleaner.

Might be a few things left to clean up, not sure at the moment.
- [x] check for unused dependencies

### CODE REVIEW

**Comment by buchanae** [comment]
Also closes #294

**Comment by buchanae** [comment]
The latest commit adds content negotiation so that `/v1/tasks` works as a dashboard URL as well as an API endpoint.

**Comment by adamstruck** [comment]
I noticed that when there are multiple pages of results tasks are not returned in sorted order. They are sorted within a single page, but then the second page ends up having the newest tasks. 

Also I am getting an HTTP handler error:

```
server               HTTP handler error
error                Not Found
time                 2017-11-06T09:11:45-08:00
url                  /favicon.ico
```

**Comment by adamstruck** [comment]
404 handling is broken

**Comment by buchanae** [comment]
Make pagination a button

**Comment by buchanae** [comment]
I think I've addressed the outstanding TODOs

**Comment by adamstruck** [comment]
This will be a big improvement to the dashboard. 

Everything looks good.  Once the tests pass I'd be happy to merge this in.

**Pull request merged**
