### PR TITLE
build: 0.6.0 and Goreleaser

### PR DESCRIPTION
**Pull request by buchanae**
This continues to address #186 by using [goreleaser](https://goreleaser.com/#introduction), adding a release notes generator, and removing the release notes from the website content.

Also updates the website for a 0.6.0 release

### CODE REVIEW

**Comment by adamstruck** [comment]
Can you confirm that the docker image build works? Looking at goreleaser's docs and their docker sections either declare `goos`, `goarch` and/or  `binary` in the docker section. 

Please squash these commits.

**Comment by buchanae** [comment]
```
docker run ohsucompbio/funnel:0.6.0-prerelease version
git commit: cc27972
git branch: goreleaser
git upstream:
build date: 2018-03-13T22:55:20Z
version: 0.6.0
```

Seems to work.

**Comment by buchanae** [comment]
Tried rebasing, but it fails on some weird submodule error:
```
git rebase -i HEAD~15
[detached HEAD 897cd22] build: use goreleaser release notes generation
 Date: Tue Mar 13 11:23:23 2018 -0700
 8 files changed, 521 insertions(+), 708 deletions(-)
 create mode 100644 .goreleaser.yml
 rewrite docs/funnel-config-examples/default-config.yaml (87%)
 create mode 100644 util/github-release-notes/main.go
 rewrite website/content/download.md (86%)
error: Updating the following directories would lose untracked files in it:
	vendor/github.com/google

Aborting
fatal: cherry-pick failed
Could not apply 6ec5896de73d775c027696f0d798989e84674b4b... build: add github vendored lib
```

**Comment by buchanae** [comment]
closed in favor of #510

**Pull request closed without merging**
