### PR TITLE
Move python tests to Go

### PR DESCRIPTION
**Pull request by buchanae**
Based on the funnel run PR, so adding do not merge

### CODE REVIEW

**Comment by buchanae** [comment]
The travis builds are 1-2 minutes faster for this branch, which is not as great as I was hoping, but still a nice improvement. Looks like the majority of our build time is in cloning submodules (40s), linting (25 s), building (20s), and testing (20-30s).

**Comment by buchanae** [comment]
Took me awhile to figure out that the hardlink test in python was testing hardlinking of inputs, not outputs (which is what my converted Go test was for). 

Hardlinking outputs works on my mac, but not in travis nor exastack, because the file is owned by root (the container user). I tried to implement setgid, but it didn't help. In the end, I gave up.

**Comment by buchanae** [comment]
I think we can close #18 #38 and #105 with this

**Comment by adamstruck** [comment]
Looks good to me. 👍

**Pull request merged**
