### PR TITLE
database/mongo: add task state counts to service info

### PR DESCRIPTION
**Pull request by buchanae**
Adds task state counts to the service info endpoint for mongo.

### CODE REVIEW

**Comment by buchanae** [comment]
Added node metrics to prometheus. Closes #470

**Comment by adamstruck** [comment]
A few comments:
- You need to run `dep ensure` to update Funnel's dependencies
- It would be nice if the task state counts had a place in the web dashboard
- Some docs around the prometheus metrics would be helpful

**Comment by buchanae** [comment]
> Also why did you copy http.proto and annotations.proto rather than use the vendored version?

I think these aren't vendored since the switch to `dep`. I thought it was simpler to just copy these two, rather than submodule the whole repo.

**Comment by buchanae** [comment]
Also needs:
- [ ] tests

**Comment by buchanae** [comment]
> It would be nice if the task state counts had a place in the web dashboard

At first I added this to the task list page, but then I realized it might be confusing in conjunction with the task filters, so I put it on the service info page as a simple fix. We can revisit something more advanced in the future.

**Comment by adamstruck** [comment]
looks good 👍

**Pull request merged**
