### PR TITLE
updates to get everything working with go 1.18

### PR DESCRIPTION
**Pull request by adamstruck**
Works for me - thought it could be useful given the ongoing compliance work I have seen.

### CODE REVIEW

**Comment by kellrott** [comment]
We've been working on getting up to TES 1.1 compliance. We'll need to review this against all the changes in #716

**Comment by lbeckman314** [comment]
This is great! We've just recently been [getting past a logging concurrency bug](https://github.com/ohsu-comp-bio/funnel/actions/runs/5536677773) with MongoDB and Badger that has been blocking the PR in #716. I'll try rebasing that branch and this one to reconcile the changes into a mergeable PR and will update here. Thanks Adam!

**Comment by adamstruck** [comment]
Looks like this PR can probably just be closed in favor of https://github.com/ohsu-comp-bio/funnel/pull/716. 

You may want to use the ‘.golangci.yml’ file and compare the proto code generation command in the Makefile.

**Comment by lbeckman314** [comment]
Cleaning up PR's but making a note of this to revisit the [Proto discussion](https://github.com/ohsu-comp-bio/funnel/pull/716#discussion_r1375155983) and proto code generation as that could definitely be improved on now that compliance tests are happy.

> Looks like this PR can probably just be closed in favor of #716.
> 
> You may want to use the ‘.golangci.yml’ file and compare the proto code generation command in the Makefile.

We're currently manually patching the tes.proto file with explicit views (minimal, basic, full) and using a custom marshaller ([marshal.go](https://github.com/ohsu-comp-bio/funnel/blob/release/0.11.0-rc.1/server/marshal.go)) in order to get around the problem of protobuf not emitting empty slices ([marshal_jsonpb.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/marshal_jsonpb.go#L85-L91)).

This could be improved in a couple ways, including:
1. Updating the proto code generator to include the the views enum value
2. Replacing our [marshal.go](https://github.com/ohsu-comp-bio/funnel/blob/release/0.11.0-rc.1/server/marshal.go) with an updated version of [marshal_jsonpb.go](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/marshal_jsonpb.go#L85-L91) that outputs empty slices

Updating the code generator would very likely be the simplest option with implementing the custom marshaler being a backup.

**Pull request closed without merging**
