### PR TITLE
worker: handle docker exit code 125 as syserr

### PR DESCRIPTION
**Pull request by buchanae**

### CODE REVIEW

**Comment by adamstruck** [comment]
Not sure how I feel about this yet. 

Things to consider:
* It's possible to have the command in the container return 125. 
* Other exit codes with special meaning in docker (https://docs.docker.com/engine/reference/run/#exit-status).

**Comment by buchanae** [comment]
Unlikely the container will return 125 and it's an improvement over thinking these failures are coming from the container. We can move to the docker client later to further improve this, maybe.

code 126 and 127 are both related to the command running inside the container, so should communicate that the executor command is wrong.

**Comment by adamstruck** [comment]
OK. Add a test and I'll merge it.

**Comment by buchanae** [comment]
I don't think there's an easy way to force docker to return a 125 error, since it's a daemon issue.

**Comment by adamstruck** [comment]
An invalid flag would do it, but thinking about it there isn't a good way to make the worker do that either.

**Comment by adamstruck** [comment]
if the executor references an image that does not exist then docker exits with 125

**Comment by buchanae** [comment]
I don't have a good enough reason for this.

**Pull request closed without merging**
