### PR TITLE
server: indents for JSON responses

### LINKED ISSUE #155: `funnel task get` dumps JSON message with missing exit code log when exit code is zero.

### PR DESCRIPTION
**Pull request by buchanae**
I added JSON pretty printing, because why not.

### CODE REVIEW

**Comment by adamstruck** [comment]
Please squash these commits.

**Comment by buchanae** [comment]
Done

**Comment by adamstruck** [comment]
I think that this PR breaks the expected behavior when requesting a particular task view.

$ curl -X GET http://localhost:8000/v1/tasks/b84u9fnpbjg5tks1p35g?view=MINIMAL
```
{
   "id": "b84u9fnpbjg5tks1p35g",
   "state": "QUEUED",
   "name": "",
   "description": "",
   "inputs": [
   ],
   "outputs": [
   ],
   "resources": null,
   "executors": [
   ],
   "volumes": [
   ],
   "tags": {
   },
   "logs": [
   ],
   "creationTime": ""
```

**Comment by buchanae** [comment]
Ah, good point, that does seem strange, even though the data isn't actually being transmitted.

**Comment by adamstruck** [comment]
The cmd/task CLI commands use their own marshaller. The return value of curl and the funnel cli should be consistent.

**Comment by buchanae** [comment]
I've removed the `EmitDefaults`. I'll have to revisit that. What's left here is pretty printing (indenting) JSON by default.

**Comment by buchanae** [comment]
Added marshaler to the `tes` package and shared with the rest of code for more consistency.

Closes #323

**Comment by buchanae** [comment]
Unfortunately, this doesn't pretty print in the browser, but it does improve curl output. I'll have to follow up on the browser later.

**Pull request merged**
